"use client"
import Navbar from '@/components/layout/Navbar'
import './globals.css'
import Footer from '@/components/layout/Footer'
import { Suspense, useEffect, useState } from 'react'
import Loading from './loading'

const metadata = {
  title: 'Green Powered Systems LTD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, [3000]);
  }, []);


  return (
    <html lang="en">
      <body>
        {
          loading ? <div className="flex justify-center items-center w-full h-[100vh] flex-col mb-4">
            <Loading />
          </div> :
            <>
              <Navbar />
              {children}
              <Footer />
            </>
        }
      </body>
    </html>
  )
}
