import Navbar from '@/components/layout/Navbar'
import './globals.css'
import Footer from '@/components/layout/Footer'

export const metadata = {
  title: 'Green Powered Systems LTD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
